### ISSUE TITLE
Limit concurrency with Mutex?

### ISSUE THREAD

**Issue by joerick** [DirtyHairy/async-mutex#12]
Hi! Thank you for this excellent library. I'm kind of amazed that it isn't more popular given how much we rely on it.

I was wondering if there's a possibility the library could be expanded to limit the number of concurrent accesses - to something greater than 1?

My use case is resizing and uploading a lot of images - with the absence of back-pressure the code races through the resize step, allocating tons of memory even though they're only uploaded slowly. So I'd like to throttle this, but putting the 'resize and upload' step into a Mutex would be wasteful, as I can probably afford 4x concurrency.

Maybe there's a better word for this than mutex as well - I think perhaps ['semaphore'](https://docs.python.org/3/library/threading.html#semaphore-objects) might be the right name.

What do you think? Worth adding to this library or should I just spin something else up myself?

**Comment by DirtyHairy** [comment]
Hi Joe!

Thanks alot for the kind words 😏 I like the idea of adding a semaphore implementation. I've been planning on overhauling the library for some time now anyway, and extending it to a semaphore with `Mutex` as a special case on top of it sounds like a good plan. If you can wait for this for another week or so, I'll go for it.

Cheers
    -Christian

**Comment by joerick** [comment]
Thanks! I also came across this - https://github.com/notenoughneon/await-semaphore - but it seems more Node-centric. I'm currently using an adapted version of it in my app as I needed to get something working for now. Could be useful for inspiration!

**Comment by DirtyHairy** [comment]
Done. I still have to update the documentation and do a release, but I have overhauled the library and added a `Semaphore` and a corresponding `SemaphoreInterface`.

A semaphore starts out with a positive definite value that is decremented each time it is locked and incremented on release. Once it has reached zero `acquire` will block until it has been incremented again. The API is pretty similar to `Mutex` --- `acquire` will return a tuple of the current semaphore value and the release callback, and `runExclusive` will pass on the current semaphore value to the callback. By definition, the values returned will be within 1 .. N where N is the initial value of the semaphore.

I'll do a proper release with updated documentation in the next days, but if you feel adventurous... 😏

**Comment by joerick** [comment]
Nice! One note - I think for a semaphore `runExclusive` could be the wrong name - it's not exclusively running. Maybe just `run` would be okay?

**Comment by DirtyHairy** [comment]
I had the same inclination. However I‘d like to keep the interface consistent between `Mutex` and  `Semaphore`, and renaming the method on `Mutex` is not an option as it would break compatibility with existing code. The same issue exists with `isLocked`.

Besides, a semaphore is usually used to acquire exclusive access to one instance of a limited resource, so the naming might not be entirely bad on a second glance 😏

**Comment by DirtyHairy** [comment]
Published.
