### ISSUE TITLE
Different release lock interface

### ISSUE THREAD

**Issue by moredrowsy** [DirtyHairy/async-mutex#15]
Currently, semaphores and mutex have a return Promised of a new release function. Is there anyway to just call a release directly on the semaphore or mutex?

I have functions where I need to lock/release multiple times.
I end up having to do this:

```
const release1 = await MUTEX.acquire();
    do something
release1();
   do something
const release2 = await MUTEX.acquire();
release2();
   do something
const release3 = await MUTEX.acquire();
release3();
```

Is it possible to make it like this?

```
await MUTEX.acquire();
MUTEX.release();

do something

await MUTEX.acquire();
MUTEX.release();

do something

await MUTEX.acquire();
MUTEX.release();
```

**Comment by DirtyHairy** [comment]
I see the usecase. I'll add `mutex.release()` as an alternate API in the next release.

**Comment by DirtyHairy** [comment]
0.2.3 adds a release method to both `Mutex` and `Semaphore` (including the `withTimeout` variants).
