### ISSUE TITLE
Error: Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by malikbenkirane** [DirtyHairy/async-mutex#17]
##### Context:
[sveltejs template](github.com/sveltejs/template) (+ rollout) +
```js
Import { Mutex } from 'async-mutex';
```
---
Removing "exports" object in package.json solves the issue.

**Comment by DirtyHairy** [comment]
This is likely to be the same issue as #14 . I just released 0.2.3 with a fix; please check if this fixes your issue as well.

Cheers
    -Christian

**Comment by malikbenkirane** [comment]
Thank you @DirtyHairy https://github.com/DirtyHairy/async-mutex/commit/b41cfc4950759925bbb82c489bf5dfb6c144f2b9 indeed, fixes the issue
