### ISSUE TITLE
feat: add force release mode to release all held locks

### ISSUE THREAD

**Issue by snowyu** [DirtyHairy/async-mutex#19]
```
semaphore.release();
```

**Comment by snowyu** [comment]
See Also: the steal option of https://developer.mozilla.org/en-US/docs/Web/API/LockManager/request

**Comment by DirtyHairy** [comment]
This sounds pretty dangerous. Do you have an example for a situation where this would be useful? Sorry for the long delay in replying.

**Comment by snowyu** [comment]
It should release all held locks when the js file system freed.

**Comment by DirtyHairy** [comment]
See #28 .
