### ISSUE TITLE
A small improvement 

### ISSUE THREAD

**Issue by ironbone** [DirtyHairy/async-mutex#2]
The 
runExclusive()
takes as a parameter a function which returns a Promise.
Why not enable also to call this method  with just a Promise?

**Comment by DirtyHairy** [comment]
Hi @ironbone !

I am not quite clear what you want to achieve here. `runExclusive` will schedule the supplied callback to run once the mutex becomes available. What should the effect of calling `runExclusive` with just a promise be?

Cheers
-Christian

**Comment by ironbone** [comment]
Sorry - I was to fast thinking. I will have no sens. Sorry.

**Comment by DirtyHairy** [comment]
No worries :smirk:

**Comment by invegat** [comment]
Is there any way to pass data into mutex.acquire?   I need to call this url with a different offset 1392 times.   `https://www.ncdc.noaa.gov/cdo-web/api/v2/stations?limit=${blk_length}&offset=${offset}`
