### ISSUE TITLE
NPM documentation improvement

### ISSUE THREAD

**Issue by shasaur** [DirtyHairy/async-mutex#20]
I spent about 30mins-1hour debugging why my `mutex.release()` was breaking. Turns out I needed to use the releaser returned from the `mutex.acquire()`.

I did this because I was skimming the NPM readme which shows example of `mutex.release()`.

I have two possible suggestions for anyone that has the same issue:

- I assume the "WARNING: Using this API comes with the inherent danger of releasing a mutex locked in an entirely unrelated place. Use with care." is meant for this, so moving it to the top of the 'Alternate release API' section (before the code examples) so that it's easier to notice for people skimming the docs would be really nice
- Changing the naming of `mutex.release()` to be `mutex.semaphoreRelease()` to make it obvious that it's probably not what you're looking for as specifically acts directly on the semaphore itself inside the mutex

Btw, awesome work on this library, it's super useful!

**Comment by DirtyHairy** [comment]
Thanks for the remark. In hindsight I am not very happy with my decision to add this API --- it has the potential for causing issues if not used carefully, and most use cases are covered by `Mutex::runExclusive`. However, I don't like breaking changes to APIs, so I won't rename it, but I may well remove it in the next major version.

I have restructured the documentation and added a warning also to the code; I hope this helps. I have also added an exception to `Semaphore::release` for concurrency > 1 --- this will not work as most people expect it.

Cheers
    -Christian
