### ISSUE TITLE
Mutex guarantees FIFO?

### ISSUE THREAD

**Issue by mannharleen** [DirtyHairy/async-mutex#26]
Is it guaranteed that the mutex will be released in the same order that they are requested?

In the other words, the following should print 0 to 10 in that order.
```js
var Mutex = require('async-mutex').Mutex;
const mutex = new Mutex();

for (let i=0; i<=10; i++){    
    let release = await mutex.acquire();
    console.log(`mutex acquired by i=${i}`)
    i === 0 ? setTimeout(release, 2000) : release()
}
```

**Comment by DirtyHairy** [comment]
Yes, locks are queued and resolved in the order in which they were were registered, FIFO style.
