### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by iambumblehead** [DirtyHairy/async-mutex#30]
@DirtyHairy thank you for this excellent package! I dropped it into a situation that needed it and it worked right away with no fuss!

Politely, I think it was too hard to find this package. I believe _this package_ is the one that most people will want to use for handling async mutexes and semaphores. I almost missed this package when searching for it.

Thank you for solving this problem for us!

**Comment by DirtyHairy** [comment]
Thanks alot for your kind words, you're welcome 😏 It is nice to see that this library is actually useful for others.
