### ISSUE TITLE
Clarify in docs that the release function returned by acquire can be called multiple times

### ISSUE THREAD

**Issue by ztane** [DirtyHairy/async-mutex#38]
...  and that release unlocks only once. The docs are not clear on that, but it seems that the code is written so.

**Comment by CMCDragonkai** [comment]
Is the async-mutex here re-entrant? How does this impact calling release multiple times?

**Comment by DirtyHairy** [comment]
The release function returned by `acquire()` is valid only for this particular lock and can be safely called multiple times --- the first invocation releases the lock, and all following calls are noops.

**Comment by DirtyHairy** [comment]
Done.
