### ISSUE TITLE
Can `waitForUnlock` be affected by `withTimeout` decorator?

### ISSUE THREAD

**Issue by CMCDragonkai** [DirtyHairy/async-mutex#53]
I want to use the `withTimeout` to wait for a lock to be unlocked, but only until a particular timeout.

**Comment by DirtyHairy** [comment]
It is affected no (with version 0.4.0 😏 )

**Comment by CMCDragonkai** [comment]
Do you mean `now`?

**Comment by DirtyHairy** [comment]
Oops, `s/no/now/` indeed 😏
