### ISSUE TITLE
Would it always be `locked` if we initialize the semaphore with a negative integer?

### ISSUE THREAD

**Issue by AkatQuas** [DirtyHairy/async-mutex#62]
As mentioned in the document, 

```markdown
...
A semaphore is a data structure that is initialized to **an arbitrary integer** value and that
can be locked multiple times.
...
```

With the implementation for `isLocked`。

https://github.com/DirtyHairy/async-mutex/blob/3d2d987e60799d0fa222f1df8f99fc90ed570bfd/src/Semaphore.ts#L44-L46

So, it seems the semaphore is always locked if we create it with negative value.

```ts
const semaphore = new Semaphore(-1);
```

Does it really make sense to allow negative value for initialization?

**Comment by DirtyHairy** [comment]
`isLocked` returning false just tells you that `acquire` will not resolve until the semaphore is released to a positive value again. There are scenarios in which the semaphore is used to dispatch a group of waiting "worker" that wait for shared resources, and for those cases, an initial negative value is valid and means that no worker will start until resources are availabel (and the semaphore is "released"). See #50 for a discussion.
