### ISSUE TITLE
Request: Priority Queue

### ISSUE THREAD

**Issue by dmurvihill** [DirtyHairy/async-mutex#73]
I'm synchronizing a CSRF token that changes every time I make a request and I want to fall back to resetting the session if I get a CSRF verification error.

I want the reset code to have a higher priority than other waiting tasks, so that the other tasks can get a fresh CSRF token before they are scheduled.

Is this a feature you are interested in? If so, I will take some time to implement it on Monday.

**Comment by DirtyHairy** [comment]
Hi @dmurvihill !

Thanks for your offer. So, what you are basically suggesting is specifying a priority to `acquire` and friends, and passing the lock to the waiter with the highest priority, right? I think this would be an interesting feature.

**Comment by dmurvihill** [comment]
Yeah, that's the thought. I'll get started.

**Comment by DirtyHairy** [comment]
... merged and released as 0.5.0 . Again, thanks a ton for your contribution @dmurvihill !

**Comment by dmurvihill** [comment]
Happy to be of service.
