### ISSUE TITLE
By using `withTimeout` the lock is not released as expected

### ISSUE THREAD

**Issue by mytharcher** [DirtyHairy/async-mutex#84]
I made a simple test case like this:

```
it('withTimeout', async () => {
    const lock = withTimeout(new Mutex(), 200);
    const r1 = await lock.acquire();
    expect(lock.isLocked()).toBe(true);
    await sleep(300);
    // expect the lock should be released automatically due to timeout
    expect(lock.isLocked()).toBe(false); // failed as it is `true` in fact
})
```

Did I miss anything? Or did I misunderstand the `withTimeout`?

**Comment by mytharcher** [comment]
Sorry. I found the explanation of `withTimeout` as the title described in the doc:

> ## Limiting the time waiting for a mutex or semaphore to become available

This means it is used for timeout of acquiring. But not for timeout of releasing.

So my further question is, will this library consider the TTL for releasing, like the case I posted before?

**Comment by NoahAndrews** [comment]
Yep, this mutex library can't force your code to exit. This should be closed as not planned.

**Comment by mytharcher** [comment]
Thanks for your explanation. I just make a wrapper in my workaround for this.
