### ISSUE TITLE
Optional acquire timeout?

### ISSUE THREAD

**Issue by cristianoccazinsp** [DirtyHairy/async-mutex#9]
It would be good to also provide a timeout argument to acquire. If the mutex is not acquired in that time, reject the promise.

**Comment by thomasf** [comment]
I'd personally prefer not to have this feature added, mutexes are simple locking primitives and IMO they should not try to be something else..

**Comment by thomasf** [comment]
If it were to be added I'd prefer a different class implementation for each type of locking mechanism.

**Comment by DirtyHairy** [comment]
> If it were to be added I'd prefer a different class implementation for each type of locking mechanism.

That's why I haven't done anything on this issue yet: I don't want to add a timeout to the Mutex class itself. However, I am open to adding a wrapper class that provides this functionality to the package.

**Comment by DirtyHairy** [comment]
I just released version 0.2.1. The library now provides a `withTimeout` decorator that adds timeout behavior to both the `Mutex` and the new`Semaphore`. Check out the readme for more documentation.

**Comment by cristianocca** [comment]
Loved the approach!
